import '../../public/style/globals.css'
import Footer from './common/footer'
import Header from './common/header'

export const metadata = {
  title: 'Sunderban Wealdcamp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
